<?php
$domain_lists = array(
'australiaquestion.com',
//'bamahasquestion.com',
'barbadosquestion.com', 'brazilquestion.com',
'canadaquestion.com',
//'chinaquestion.com',
'guangzhouquestion.com',
'dubaiquestion.com',
'egyptquestion.com', 'europequestion.com',
'hong-kongquestion.com',
'icelandquestion.com', 'indiaquestion.com',
'indonesiaquestion.com',
'japanquestion.com',
'kenyaquestion.com', 'koreaquestion.com',
'laosquestion.com',
'malaysiaquestion.com', 'mexicoquestion.com',
//'monacaquestion.com',
'new-zealandquestion.com',
'phillipinesquestion.com',
'singaporequestion.com',
'south-africaquestion.com',
'taiwanquestion.com', 'thailandquestion.com', 'tibetquestion.com', 'turkeyquestion.com',
//'United States of Americaquestion.com',
'vaticanquestion.com', 'vietnamquestion.com'
);